name: "Second flow"

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
      - 'hotfix/**'

jobs:
  TerraformInit:
    name: TerraformInit
    runs-on: suraj-maharaj
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
